### PR TITLE
Fix compile error in lcd_move_e calls

### PR DESCRIPTION
**Pull request by thinkyhead**
Fix a compile error introduced in #98 due to missing semicolons.

### CODE REVIEW

**Comment by emartinez167** [comment]
With EXTRUDERS = 2 compiler fails with the following:

/var/folders/7s/_12bnnk90y72chfwxb19sj_80000gn/T/build2376214899307737121.tmp/ultralcd.cpp: In function 'void lcd_move_menu_axis()':
/var/folders/7s/_12bnnk90y72chfwxb19sj_80000gn/T/build2376214899307737121.tmp/ultralcd.cpp:165:34: error: invalid conversion from 'void (*)(uint8_t) {aka void (*)(unsigned char)}' to 'menuFunc_t {aka void (*)()}' [-fpermissive]
         menu_action_ ## type(args); \
                                  ^
/var/folders/7s/_12bnnk90y72chfwxb19sj_80000gn/T/build2376214899307737121.tmp/ultralcd.cpp:798:5: note: in expansion of macro 'MENU_ITEM'
     MENU_ITEM(submenu, MSG_MOVE_E, lcd_move_e);
     ^
/var/folders/7s/_12bnnk90y72chfwxb19sj_80000gn/T/build2376214899307737121.tmp/ultralcd.cpp:79:15: error:   initializing argument 1 of 'void menu_action_submenu(menuFunc_t)' [-fpermissive]
   static void menu_action_submenu(menuFunc_t data);
               ^
Error compiling.

**Comment by clefranc** [comment]
@thinkyhead Same thing as @emartinez167 here!

**Comment by clefranc** [comment]
@gralco ???

**Comment by gralco** [comment]
@clefranc @thinkyhead @emartinez167 
I apologize for not testing it again. This commit should fix the compilation error (it did for me): https://github.com/gralco/MarlinDev/commit/6b137e519fee827a0379e62175849c81bf2fec59

**Comment by gralco** [comment]
This line is required: https://github.com/gralco/MarlinDev/commit/6b137e519fee827a0379e62175849c81bf2fec59#diff-34f7cdd618621ae7d8c113cf0b86a2f4R768

**Comment by clefranc** [comment]
@gralco Thank you sir.

**Comment by gralco** [comment]
@clefranc 
No problem, please let me know if you experience any other issues with my PR.

**Comment by gralco** [comment]
@thinkyhead @clefranc @emartinez167 

The condition EXTRUDERS > 1 needs to be removed as I've done in this commit: https://github.com/gralco/MarlinDev/commit/704916fc17d68a95d4c0955a1ba0fa6a5913a94f

**Comment by clefranc** [comment]
@gralco Can you make the LCD menu look like this:

1 extruder:
```
Extruder
```
2 or more extruders:
```
Extruder1
Extruder2
...
```
I think it'll be more consistent with the current scheme, ie zero-based in code, one-based on the LCD display.

**Comment by gralco** [comment]
@clefranc @thinkyhead 
Please take a look at this commit: https://github.com/gralco/MarlinDev/commit/75c75190675dd9fd5c2287b59bec68dce98dffec
The naming convention is followed.
I've tested it; it compiles and displays as expected (tested with *EXTRUDERS ==1* and *EXTRUDERS == 2*).
Please try to incorporate/merge these changes.

**Comment by clefranc** [comment]
@gralco See my comments in your commit.

**Comment by gralco** [comment]
@clefranc 
Thank you so much for reviewing my working, please take a look at https://github.com/gralco/MarlinDev/commit/9019e7e3d5599ee0e00ed838dc847c68d697b366 to make sure all is good.

**Comment by clefranc** [comment]
@gralco My pleasure, I think you're good for a final PR.

**Comment by gralco** [comment]
@clefranc 
Should I create a new pull request or can my work be merged as is?

**Comment by clefranc** [comment]
@gralco You must create a PR, usually @thinkyhead do these fix "les deux doigts dans le nez", but he's not around, and I don't have credential to do merges.
